/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package financeadvisor.Forms;

import financeadvisor.FormData;
import financeadvisor.PaymentEntry;
import financeadvisor.Tool;
import javax.swing.ButtonGroup;
import javax.swing.JList;
import javax.swing.border.BevelBorder;

/**
 *
 * @author joomlah
 */
public class Finance extends javax.swing.JFrame {
    
    private FormData data;
    
    /**
     * Creates new form Finance
     */
    public Finance() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        initFormData();
    }
    
    public void initFormData() {
        
        ButtonGroup btnGroup = new ButtonGroup();
        btnGroup.add(dailyRBtn);
        btnGroup.add(weeklyRBtn);
        btnGroup.add(monthlyRBtn);
        btnGroup.add(yearlyRBtn);
        weeklyRBtn.setSelected(true);
        
        
        data = new FormData();
        
        
        updateLblNoSign(hoursWorkedLbl, data.getWorkHours());
        
//        updateLbl(totalIncomeLbl, data.getTotalIncome());
        
        
        expenseLst.setModel(data.getModel());
        expenseLst.setSelectedIndex(0);
        
        
//        double spendingTotal = getTotalSpending(data.getModel());
//        data.setSpendingTotal(spendingTotal);
//        updateLbl(totalSpendingLbl, data.getTotalSpending());

        
//        double workIncome = data.getWorkIncome();
//        double grandTotal = workIncome - spendingTotal;
//        data.setGrandTotal(grandTotal);
//        updateLbl(grandTotalLbl, data.getGrandTotal());

        updateLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hoursBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hoursWorkedLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        totalIncomeLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        expenseLst = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        addExpenseBtn = new javax.swing.JButton();
        removeExpenseBtn = new javax.swing.JButton();
        editExpenseBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        totalSpendingLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        grandTotalLbl = new javax.swing.JLabel();
        dailyRBtn = new javax.swing.JRadioButton();
        weeklyRBtn = new javax.swing.JRadioButton();
        monthlyRBtn = new javax.swing.JRadioButton();
        yearlyRBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finance Advisor -- ZT V0.1");

        hoursBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hoursBtn.setToolTipText("Change the Hours Worked");
        hoursBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoursBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hoursBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hoursBtnMouseReleased(evt);
            }
        });

        jLabel1.setText("Hours");

        hoursWorkedLbl.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        hoursWorkedLbl.setText("hoursWorked");

        javax.swing.GroupLayout hoursBtnLayout = new javax.swing.GroupLayout(hoursBtn);
        hoursBtn.setLayout(hoursBtnLayout);
        hoursBtnLayout.setHorizontalGroup(
            hoursBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoursBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hoursBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(hoursWorkedLbl)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hoursBtnLayout.setVerticalGroup(
            hoursBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoursBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hoursWorkedLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("Positive Income");

        jLabel3.setText("Income");

        totalIncomeLbl.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        totalIncomeLbl.setText("totalIncome");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(totalIncomeLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalIncomeLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        expenseLst.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        expenseLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                expenseLstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(expenseLst);

        jLabel2.setText("Expenses");

        jLabel4.setText("Date Added:");

        dateLbl.setText("dateLbl");

        jLabel6.setText("Description:");

        descriptionArea.setEditable(false);
        descriptionArea.setColumns(20);
        descriptionArea.setLineWrap(true);
        descriptionArea.setRows(5);
        descriptionArea.setText("Description Text");
        jScrollPane2.setViewportView(descriptionArea);

        addExpenseBtn.setText("Add");
        addExpenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenseBtnActionPerformed(evt);
            }
        });

        removeExpenseBtn.setText("Remove");
        removeExpenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeExpenseBtnActionPerformed(evt);
            }
        });

        editExpenseBtn.setText("Edit");
        editExpenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editExpenseBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setToolTipText("Total Spending");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel5.setText("Spending");

        totalSpendingLbl.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        totalSpendingLbl.setText("totalSpending");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(totalSpendingLbl)
                    .addComponent(jLabel5))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalSpendingLbl)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel7.setText("Grand Total");

        grandTotalLbl.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        grandTotalLbl.setText("grandTotalLbl");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(grandTotalLbl))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(grandTotalLbl)
                .addContainerGap())
        );

        dailyRBtn.setText("Daily");

        weeklyRBtn.setText("Weekly");

        monthlyRBtn.setText("Monthly");

        yearlyRBtn.setText("Yearly");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addExpenseBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editExpenseBtn))
                            .addComponent(removeExpenseBtn)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dailyRBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weeklyRBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthlyRBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearlyRBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hoursBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hoursBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dailyRBtn)
                    .addComponent(weeklyRBtn)
                    .addComponent(monthlyRBtn)
                    .addComponent(yearlyRBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(dateLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addExpenseBtn)
                    .addComponent(editExpenseBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeExpenseBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hoursBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoursBtnMouseClicked
        // TODO add your handling code here:
        
        HoursWorked hw = new HoursWorked(this, true);
        hw.setVisible(true);
        
        // --**This is aids and needs fixed**--
        
        // Continues AFTER HoursWorked Dialog is closed!
        updateLblNoSign(hoursWorkedLbl, data.getWorkHours());
        
        // ** THIS IS COMPLETE AIDS
//        String hoursString = hoursWorkedLbl.getText();
//        
//        double newHours = Double.parseDouble(hoursString);
//        
//        double newIncomeTotal = newHours * data.getPayRate();
//        data.setWorkIncome(newIncomeTotal);
        
        // ** END OF COMPLETE AIDS
        
        //updateLbl(totalIncomeLbl, newIncomeTotal);
//        updateLbl(totalIncomeLbl, data.getTotalIncome());
        
//        String newIncomeString = Tool.roundToString(newIncomeTotal);
//        totalIncomeLbl.setText("$" + newIncomeString);
        
//        double incomeSpending = data.getTotalSpending();
//        double newGrandTotal = newIncomeTotal - incomeSpending;
//        data.setGrandTotal(newGrandTotal);
//        updateLbl(grandTotalLbl, data.getGrandTotal());
//        String gtString = Tool.roundToString(newGrandTotal);
//        grandTotalLbl.setText("$" + gtString);

        updateLabels();
        
    }//GEN-LAST:event_hoursBtnMouseClicked

    private void hoursBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoursBtnMousePressed
        // TODO add your handling code here:
        hoursBtn.setBorder(new BevelBorder(BevelBorder.LOWERED));
    }//GEN-LAST:event_hoursBtnMousePressed

    private void hoursBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoursBtnMouseReleased
        // TODO add your handling code here:
        hoursBtn.setBorder(new BevelBorder(BevelBorder.RAISED));
    }//GEN-LAST:event_hoursBtnMouseReleased

    private void removeExpenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeExpenseBtnActionPerformed
        // TODO add your handling code here:
        int i = expenseLst.getSelectedIndex();
        
        if (i > -1) {
            //PaymentEntry pe = (PaymentEntry) data.getModel().getElementAt(i);
            //double value = pe.getValue();
            
            /** OLD MODIFIED CODE
            double oldGrandTotal = data.getGrandTotal();
            double grandTotal = oldGrandTotal + value;
            data.setGrandTotal(grandTotal);
            updateLbl(grandTotalLbl, grandTotal);
            */
            
//            String s = Tool.roundToString(grandTotal);
//            grandTotalLbl.setText("$" + s);
            
            data.getModel().remove(i);
            expenseLst.setModel(data.getModel());
            
            // NEW MODIFIED CODE
//            updateLbl(grandTotalLbl, data.getGrandTotal());
            // *****************************************
            
//            double totalSpending = getTotalSpending(data.getModel());
//            data.setSpendingTotal(totalSpending);
//            updateLbl(totalSpendingLbl, data.getTotalSpending());
//            s = Tool.roundToString(totalSpending);
//            totalSpendingLbl.setText("$" + s);

            updateLabels();

            dateLbl.setText("---");
            descriptionArea.setText("");
            
        }
        
    }//GEN-LAST:event_removeExpenseBtnActionPerformed

    private void expenseLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_expenseLstValueChanged
        // TODO add your handling code here:
        int i = expenseLst.getSelectedIndex();

        if (i > -1 && data.getModel() != null) {
            PaymentEntry temp = (PaymentEntry) data.getModel().getElementAt(i);
            dateLbl.setText(temp.getDateString());
            descriptionArea.setText(temp.getDescription());
        }
        
    }//GEN-LAST:event_expenseLstValueChanged

    private void addExpenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseBtnActionPerformed
        // TODO add your handling code here:
        
        ModifyEntry me = new ModifyEntry(this, true, ModifyEntry.ModeType.ADD);
        me.setVisible(true);
        
        expenseLst.setModel(data.getModel());
        
        updateLabels();
//        updateLbl(totalSpendingLbl, data.getTotalSpending());
//        updateLbl(grandTotalLbl, data.getGrandTotal());
        
    }//GEN-LAST:event_addExpenseBtnActionPerformed

    private void editExpenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editExpenseBtnActionPerformed
        // TODO add your handling code here:
        
        if (expenseLst.getSelectedIndex() > -1) {
            ModifyEntry me = new ModifyEntry(this, true, ModifyEntry.ModeType.EDIT);
            me.setVisible(true);
            
            expenseLst.setModel(data.getModel());
            
            updateLabels();
//            updateLbl(totalSpendingLbl, data.getTotalSpending());
//            updateLbl(grandTotalLbl, data.getGrandTotal());
        }
    }//GEN-LAST:event_editExpenseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Finance().setVisible(true);
        });
    }
    
//    public double getTotalSpending(DefaultListModel m) {
//        double spendingTotal = 0;
//        for (int i = 0; i < m.size(); i++){
//            PaymentEntry p = (PaymentEntry) m.getElementAt(i);
//            
//            spendingTotal += p.getValue();
//        }
//        return spendingTotal;
//    }
    
    public void updateLabels() {
        /*
        double spendingTotal = getTotalSpending(m);
        data.setSpendingTotal(spendingTotal);
        updateLbl(l, v);
        
        double workIncome = data.getWorkIncome();
        double grandTotal = workIncome - spendingTotal;
        data.setGrandTotal(grandTotal);
        updateLbl(l, v);
        
        double newIncomeTotal = newHours * PAY_RATE;
        data.setWorkIncome(newIncomeTotal);
        updateLbl(l, v);
        
        double incomeSpending = data.getSpendingTotal();
        double newGrandTotal = newIncomeTotal - incomeSpending;
        data.setGrandTotal(newGrandTotal);
        updateLbl(l, v);
        */
        updateLbl(totalIncomeLbl, data.getTotalIncome());
        updateLbl(totalSpendingLbl, data.getTotalSpending());
        updateLbl(grandTotalLbl, data.getGrandTotal());
    }
    
    public void updateLbl(javax.swing.JLabel label, double value) {
        String s = Tool.roundToString(value);
        label.setText("$" + s);
    }
    
    public void updateLblNoSign(javax.swing.JLabel label, double value) {
        String s = Tool.roundToString(value);
        label.setText(s);
    }
    
    
//    public void setHoursWorkedText(String s) {
//        hoursWorkedLbl.setText(s);
//    }

    public FormData getData() {
        return data;
    }

    public JList<String> getExpenseLst() {
        return expenseLst;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExpenseBtn;
    private javax.swing.JRadioButton dailyRBtn;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JButton editExpenseBtn;
    private javax.swing.JList<String> expenseLst;
    private javax.swing.JLabel grandTotalLbl;
    private javax.swing.JPanel hoursBtn;
    private javax.swing.JLabel hoursWorkedLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton monthlyRBtn;
    private javax.swing.JButton removeExpenseBtn;
    private javax.swing.JLabel totalIncomeLbl;
    private javax.swing.JLabel totalSpendingLbl;
    private javax.swing.JRadioButton weeklyRBtn;
    private javax.swing.JRadioButton yearlyRBtn;
    // End of variables declaration//GEN-END:variables
}
